version: '3.0'

services:
  railgun:
    image: dockhero/cloudflare-railgun
    command: sh -c "/bin/everyboot; /usr/bin/rg-listener -config=/etc/railgun/railgun.conf"
    ports:
      - "2408:2408"
    environment:
      MEMCACHED_SERVERS: "memcache:11211"
      ACTIVATION_TOKEN: ${RAILGUN_ACTIVATION_KEY}
      ACTIVATION_RAILGUN_HOST: ${DOCKHERO_HOST}
    restart: "on-failure:10"
    volumes:
      - firstboot:/etc/firstboot

  memcache:
    image: dockhero/memcached
    command: memcached -m 128
    restart: "on-failure:10"

volumes:
  firstboot:
    driver: local
